### PR TITLE
Capture and upload image with statistics, header and gradient views

### PR DESCRIPTION
**Pull request by callum-code**
Enjoy :)

### CODE REVIEW

**Review by Mehequanna — APPROVED** [review]
Nice! I can't believe you did that so fast :)

**Review by Mehequanna — CHANGES_REQUESTED** [review]
The code looks good. I keep getting errors or crashing. The app is saying it can't find the image context. Are you seeing this?

**Comment by callum-code** [comment]
> The code looks good. I keep getting errors or crashing. The app is saying it can't find the image context. Are you seeing this?

Nope, not at all. Could u put up a stack trace?

**Comment by Mehequanna** [comment]
@callum-code Here is the stack trace. I got the same crash in testflight. So there may be a trace there that's useful too.

Screen Shot 2021-05-17 at 10 54 15 PM

**Comment by callum-code** [comment]
Ok, I see the stack trace in TestFlight. I can fix the fatal error easily, just not why it occurred. `Unable to get image metadata` meant that after capturing the image if was unable to get the png data. Were you running this on ARKit or ARCore?

**Comment by callum-code** [comment]
Also, when `ShareSheetViewController` is displayed, does the image include the statistics, header and gradient?

**Comment by Mehequanna** [comment]
@callum-code I believe so yes.

**Review by Mehequanna — APPROVED** [review]
I just checked this again. Seems to be working. It must have been an issue with iOS. Sorry I'm just getting back to this, apparently this last month got crazy out of hand. I didn't even noticed you pushed a new commit :(

**Comment by callum-code** [comment]
All good!

**Pull request merged**
